
services:
  app:
    restart: always
    build: ./
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy  # Ждем, пока БД будет здорова
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=music-library
    volumes:
      - ./configs/config.yml:/app/configs/config.yml
    command: ["sh", "-c", "./main configs/config.yml"]

  db:
    restart: always
    image: postgres:alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=music-library
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
