services:
  app:
    restart: always
    build: ./ 
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env 
    volumes:
      - ./configs/config.yml:/app/configs/config.yml
    command: ["sh", "-c", "./main configs/config.yml"]

  db:
    restart: always
    image: postgres:alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env  
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
